packages:
  - 'packages/*'

catalog:
  '@open-wc/testing': '^4.0.0'
  '@types/mocha': '^10.0.10'
  '@web/test-runner': '^0.18.2'
  bootstrap-italia: 'github:italia/bootstrap-italia#67b3a245b219fe6ac17277193caebbd8e4824797'
  lit: '^3.3.0'
  sass: '^1.89.0'
  typescript: '^5.5.3'
