packages:
  - 'packages/*'

catalog:
  '@open-wc/testing': '^4.0.0'
  '@types/mocha': '^10.0.10'
  '@typescript-eslint/eslint-plugin': '^7.16.0'
  '@typescript-eslint/parser': '^7.16.0'
  '@web/test-runner': '^0.18.2'
  bootstrap-italia: 'github:italia/bootstrap-italia#67b3a245b219fe6ac17277193caebbd8e4824797'
  eslint: '^8.57.0'
  eslint-config-prettier: '^9.1.0'
  eslint-plugin-storybook: '^0.12.0'
  lit: '^3.3.0'
  prettier: '^3.3.2'
  sass: '^1.89.0'
  typescript: '^5.5.3'
